FROM node:lts

ENV NODE_ENV=production
ENV EDITOR_API_URL=https://editor.test.schul-cloud.org
ENV SERVER_API_URL=https://api.test.schul-cloud.org
ENV EDITOR_SOCKET_URL=wss://editor.test.schul-cloud.org

WORKDIR /home/node/app

COPY . .

RUN npm install
RUN npm audit fix

CMD npm run build