export const students = [
    "Jasmine Hertz",
    "Lannie Hubley",
    "Samantha Jensen",
    "Giovanna Rosebrock",
    "Corrinne Volkmann",
    "Retta Shelly",
    "Tiana Chavers",
    "Sherlyn Nichols",
    "Donnie Odom",
    "Rosanne Rapozo",
    "Anastacia Fralick",
    "Freda Mailman",
    "Winston Lamphear",
    "Therese Snay",
    "Maegan Nakashima",
    "Janessa Ewell",
    "Keshia Ocasio",
    "Sasha Garoutte",
    "Noreen Cowell",
    "Martin Gupta",
    "Isela Wein",
]
